DESCRIBE my_schema.pais;
  
INSERT INTO my_schema.pais (id,nome_ptbr,nome_eng,continente,capital) 
VALUES 
(1,'Andorra','Andorra','EU','Andorra la Vella'),
(2,'Emirados Árabes Unidos','United Arab Emirates','AS','Abu Dhabi'),
(3,'Afeganistão','Afghanistan','AS','Kabul'),
(4,'Antigua e Barbuda','Antigua and Barbuda','NA','St. John s'),
(5,'Anguilla','Anguilla','NA','The Valley'),
(6,'Albânia','Albania','EU','Tirana'),
(7,'Armênia','Armenia','AS','Yerevan'),
(8,'Antilhas Holandesas','Netherlands Antilles','NA','Willemstad'),
(9,'Angola','Angola','AF','Luanda'),
(10,'Antártica','Antarctica',' AN',''),
(11,'Argentina','Argentina','SA','Buenos Aires'),
(12,'Samoa Americana','American Samoa','OC','Pago Pago'),
(13,'Áustria','Austria','EU','Vienna'),
(14,'Austrália','Australia','OC','Canberra'),
(15,'Aruba','Aruba','NA','Oranjestad'),
(16,'Ilhas de Aland','Åland Islands','EU','Mariehamn'),
(17,'Azerbaijão','Azerbaijan','AS','Baku'),
(18,'Bósnia-herzegovina','Bosnia and Herzegowina','EU','Sarajevo'),
(19,'Barbados','Barbados','NA','Bridgetown'),
(20,'Bangladesh','Bangladesh','AS','Dhaka'),
(21,'Bélgica','Belgium','EU','Brussels'),
(22,'Burkina Faso','Burkina Faso','AF','Ouagadougou'),
(23,'Bulgária','Bulgaria','EU','Sofia'),
(24,'Bahrein, Ilhas','Bahrain','AS','Manama'),
(25,'Burundi','Burundi','AF','Bujumbura'),
(26,'Benin','Benin','AF','Porto-Novo'),
(27,'Coletividade de São Bartolomeu','Saint Barthélemy','NA','Gustavia'),
(28,'Bermudas','Bermuda','NA','Hamilton'),
(29,'Brunei','Brunei Darussalam','AS','Bandar Seri Begawan'),
(30,'Bolívia','Bolivia','SA','Sucre'),
(31,'Brasil','Brazil','SA','Brasilia'),
(32,'Bahamas, Ilhas','Bahamas','NA','Nassau'),
(33,'Butão','Bhutan','AS','Thimphu'),
(34,'Ilha Bouvet','Bouvet Island',' AN',''),
(35,'Botsuana','Botswana','AF','Gaborone'),
(36,'Belarus','Belarus','EU','Minsk'),
(37,'Belize','Belize','NA','Belmopan'),
(38,'Canada','Canada','NA','Ottawa'),
(39,'Cocos(Keeling), Ilhas','Cocos (Keeling) Islands','AS','West Island'),
(40,'Republica Democrática do Congo','Congo, the Democratic Republic of the','AF','Kinshasa'),
(41,'Republica Centro-Africana','Central African Republic','AF','Bangui'),
(42,'Congo','Congo','AF','Brazzaville'),
(43,'Suíça','Switzerland','EU','Bern'),
(44,'Costa do Marfim','Cote d Ivoire','AF','Yamoussoukro'),
(45,'Cook, Ilhas','Cook Islands','OC','Avarua'),
(46,'Chile','Chile','SA','Santiago'),
(47,'Camarões','Cameroon','AF','Yaounde'),
(48,'China','China','AS','Beijing'),
(49,'Colômbia','Colombia','SA','Bogota'),
(50,'Costa Rica','Costa Rica','NA','San Jose'),
(51,'Cuba','Cuba','NA','Havana'),
(52,'Cabo Verde','Cape Verde','AF','Praia'),
(53,'Curaçao','Curaçao','NA','Willemstad'),
(54,'Christmas, Ilha (Navidad)','Christmas Island','OC','Flying Fish Cove'),
(55,'Chipre','Cyprus','EU','Nicosia'),
(56,'Republica Tcheca','Czech Republic','EU','Prague'),
(57,'Alemanha','Germany','EU','Berlin'),
(58,'Djibuti','Djibouti','AF','Djibouti'),
(59,'Dinamarca','Denmark','EU','Copenhagen'),
(60,'Dominica, Ilha','Dominica','NA','Roseau'),
(61,'Republica Dominicana','Dominican Republic','NA','Santo Domingo'),
(62,'Argélia','Algeria','AF','Algiers'),
(63,'Equador','Ecuador','SA','Quito'),
(64,'Republica da Estônia','Estonia','EU','Tallinn'),
(65,'Egito','Egypt','AF','Cairo'),
(66,'Saara Ocidental','Western Sahara','AF','El-Aaiun'),
(67,'Eritreia','Eritrea','AF','Asmara'),
(68,'Espanha','Spain','EU','Madrid'),
(69,'Etiópia','Ethiopia','AF','Addis Ababa'),
(70,'Finlândia','Finland','EU','Helsinki'),
(71,'Fiji','Fiji','OC','Suva'),
(72,'Falkland (Ilhas Malvinas)','Falkland Islands (Malvinas)','SA','Stanley'),
(73,'Micronesia','Micronesia, Federated States of','OC','Palikir'),
(74,'Feroe, Ilhas','Faroe Islands','EU','Torshavn'),
(75,'Franca','France','EU','Paris'),
(76,'Gabão','Gabon','AF','Libreville'),
(77,'Reino Unido','United Kingdom','EU','London'),
(78,'Granada','Grenada','NA','St. George s'),
(79,'Republica da Georgia','Georgia','AS','Tbilisi'),
(80,'Guiana francesa','French Guiana','SA','Cayenne'),
(81,'Guernsey, Ilha do Canal (Inclui Alderney e Sark)','Bailiwick of Guernsey','EU','St Peter Port'),
(82,'Gana','Ghana','AF','Accra'),
(83,'Gibraltar','Gibraltar','EU','Gibraltar'),
(84,'Groenlândia','Greenland','NA','Nuuk'),
(85,'Gambia','Gambia','AF','Banjul'),
(86,'Guine','Guinea','AF','Conakry'),
(87,'Guadalupe','Guadeloupe','NA','Basse-Terre'),
(88,'Guine-Equatorial','Equatorial Guinea','AF','Malabo'),
(89,'Grécia','Greece','EU','Athens'),
(90,'Ilhas Geórgia do Sul e Sandwich do Sul','South Georgia and the South Sandwich Islands','AN','Grytviken'),
(91,'Guatemala','Guatemala','NA','Guatemala City'),
(92,'Guam','Guam','OC','Hagatna'),
(93,'Guine-Bissau','Guinea-Bissau','AF','Bissau'),
(94,'Guiana','Guyana','SA','Georgetown'),
(95,'Hong Kong','Hong Kong','AS','Hong Kong'),
(96,'Ilha Heard e Ilhas McDonald','Heard and Mc Donald Islands',' AN',''),
(97,'Honduras','Honduras','NA','Tegucigalpa'),
(98,'Republica da Croácia','Croatia (Hrvatska)','EU','Zagreb'),
(99,'Haiti','Haiti','NA','Port-au-Prince'),
(100,'Republica da Hungria','Hungary','EU','Budapest'),
(101,'Indonésia','Indonesia','AS','Jakarta'),
(102,'Irlanda','Ireland','EU','Dublin'),
(103,'Israel','Israel','AS','Jerusalem'),
(104,'Man, Ilha de','Isle of Man','EU','Douglas'),
(105,'Índia','India','AS','New Delhi'),
(106,'Território Britânico do Oceano Indico','British Indian Ocean Territory','AS','Diego Garcia'),
(107,'Iraque','Iraq','AS','Baghdad'),
(108,'Ira','Iran','AS','Tehran'),
(109,'Islândia','Iceland','EU','Reykjavik'),
(110,'Itália','Italy','EU','Rome'),
(111,'Jersey, Ilha do Canal','Bailiwick of Jersey','EU','Saint Helier'),
(112,'Jamaica','Jamaica','NA','Kingston'),
(113,'Jordânia','Jordan','AS','Amman'),
(114,'Japão','Japan','AS','Tokyo'),
(115,'Quênia','Kenya','AF','Nairobi'),
(116,'Republica Quirguiz','Kyrgyzstan','AS','Bishkek'),
(117,'Camboja','Cambodia','AS','Phnom Penh'),
(118,'Kiribati','Kiribati','OC','Tarawa'),
(119,'Comores, Ilhas','Comoros','AF','Moroni'),
(120,'São Cristovão e Neves, Ilhas','Saint Kitts and Nevis','NA','Basseterre'),
(121,'Coreia','Korea','AS','Pyongyang'),
(122,'Republica da Coreia','Republic of Korea','AS','Seoul'),
(123,'Coveite','Kuwait','AS','Kuwait City'),
(124,'Cayman, Ilhas','Cayman Islands','NA','George Town'),
(125,'Republica do Cazaquistão','Kazakhstan','AS','Astana'),
(126,'Republica Popular Democrática do Laos','Lao People s Democratic Republic','AS','Vientiane'),
(127,'Líbano','Lebanon','AS','Beirut'),
(128,'Santa Lucia','Saint LUCIA','NA','Castries'),
(129,'Liechtenstein','Liechtenstein','EU','Vaduz'),
(130,'Sri Lanka','Sri Lanka','AS','Colombo'),
(131,'Libéria','Liberia','AF','Monrovia'),
(132,'Lesoto','Lesotho','AF','Maseru'),
(133,'Republica da Lituânia','Lithuania','EU','Vilnius'),
(134,'Luxemburgo','Luxembourg','EU','Luxembourg'),
(135,'Republica da Letônia','Latvia','EU','Riga'),
(136,'Líbia','Libyan Arab Jamahiriya','AF','Tripoli'),
(137,'Marrocos','Morocco','AF','Rabat'),
(138,'Mônaco','Monaco','EU','Monaco'),
(139,'Republica da Moldávia','Republic of Moldova','EU','Chisinau'),
(140,'Montenegro','Crna Gora (Montenegro)','EU','Podgorica'),
(141,'Ilha de São Martinho (França)','Saint Martin','NA','Marigot'),
(142,'Madagascar','Madagascar','AF','Antananarivo'),
(143,'Marshall, Ilhas','Marshall Islands','OC','Majuro'),
(144,'Macedônia','Macedonia','EU','Skopje'),
(145,'Mali','Mali','AF','Bamako'),
(146,'Mianmar (Birmânia)','Myanmar','AS','Nay Pyi Taw'),
(147,'Mongólia','Mongolia','AS','Ulan Bator'),
(148,'Macau','Macau','AS','Macao'),
(149,'Marianas do Norte','Northern Mariana Islands','OC','Saipan'),
(150,'Martinica','Martinique','NA','Fort-de-France'),
(151,'Mauritânia','Mauritania','AF','Nouakchott'),
(152,'Montserrat, Ilhas','Montserrat','NA','Plymouth'),
(153,'Malta','Malta','EU','Valletta'),
(154,'Mauricio','Mauritius','AF','Port Louis'),
(155,'Maldivas','Maldives','AS','Male'),
(156,'Malavi','Malawi','AF','Lilongwe'),
(157,'México','Mexico','NA','Mexico City'),
(158,'Malásia','Malaysia','AS','Kuala Lumpur'),
(159,'Moçambique','Mozambique','AF','Maputo'),
(160,'Namíbia','Namibia','AF','Windhoek'),
(161,'Nova Caledonia','New Caledonia','OC','Noumea'),
(162,'Níger','Niger','AF','Niamey'),
(163,'Norfolk, Ilha','Norfolk Island','OC','Kingston'),
(164,'Nigéria','Nigeria','AF','Abuja'),
(165,'Nicarágua','Nicaragua','NA','Managua'),
(166,'Países Baixos (Holanda)','Netherlands','EU','Amsterdam'),
(167,'Noruega','Norway','EU','Oslo'),
(168,'Nepal','Nepal','AS','Kathmandu'),
(169,'Nauru','Nauru','OC','Yaren'),
(170,'Niue, Ilha','Niue','OC','Alofi'),
(171,'Nova Zelândia','New Zealand','OC','Wellington'),
(172,'Oma','Oman','AS','Muscat'),
(173,'Panamá','Panama','NA','Panama City'),
(174,'Peru','Peru','SA','Lima'),
(175,'Polinésia Francesa','French Polynesia','OC','Papeete'),
(176,'Papua Nova Guine','Papua New Guinea','OC','Port Moresby'),
(177,'Filipinas','Philippines','AS','Manila'),
(178,'Paquistão','Pakistan','AS','Islamabad'),
(179,'Polônia','Poland','EU','Warsaw'),
(180,'São Pedro e Miquelon','St. Pierre and Miquelon','NA','Saint-Pierre'),
(181,'Pitcairn, Ilha','Pitcairn','OC','Adamstown'),
(182,'Porto Rico','Puerto Rico','NA','San Juan'),
(183,'Palestina','Dawlat Filasṭīn','AS','East Jerusalem'),
(184,'Portugal','Portugal','EU','Lisbon'),
(185,'Palau','Palau','OC','Melekeok'),
(186,'Paraguai','Paraguay','SA','Asuncion'),
(187,'Catar','Qatar','AS','Doha'),
(188,'Reunião, Ilha','Reunion','AF','Saint-Denis'),
(189,'Romênia','Romania','EU','Bucharest'),
(190,'Republika Srbija','SÉRVIA','EU','Belgrade'),
(191,'Rússia, Federação da','Russian Federation','EU','Moscow'),
(192,'Ruanda','Rwanda','AF','Kigali'),
(193,'Arábia Saudita','Saudi Arabia','AS','Riyadh'),
(194,'Salomão, Ilhas','Solomon Islands','OC','Honiara'),
(195,'Seychelles','Seychelles','AF','Victoria'),
(196,'Sudão','Sudan','AF','Khartoum'),
(197,'Suécia','Sweden','EU','Stockholm'),
(198,'Cingapura','Singapore','AS','Singapore'),
(199,'Santa Helena','St. Helena','AF','Jamestown'),
(200,'Eslovênia','Slovenia','EU','Ljubljana'),
(201,'Svalbard e Jan Mayen','Svalbard and Jan Mayen Islands','EU','Longyearbyen'),
(202,' Republica Eslovaca','Slovakia (Slovak Republic)','EU','Bratislava'),
(203,'Serra Leoa','Sierra Leone','AF','Freetown'),
(204,'San Marino','San Marino','EU','San Marino'),
(205,'Senegal','Senegal','AF','Dakar'),
(206,'Somalia','Somalia','AF','Mogadishu'),
(207,'Suriname','Suriname','SA','Paramaribo'),
(208,'Sudao do Sul','Republic of South Sudan','AF','Juba'),
(209,'São Tome e Príncipe, Ilhas','Sao Tome and Principe','AF','Sao Tome'),
(210,'El Salvador','El Salvador','NA','San Salvador'),
(211,'São Martinho (Países Baixos)','Sint Maarten (Dutch part)','NA','Philipsburg'),
(212,'Síria','Syrian','AS','Damascus'),
(213,'Suazilândia','Swaziland','AF','Mbabane'),
(214,'Turcas e Caicos, Ilhas','Turks and Caicos Islands','NA','Cockburn Town'),
(215,'Chade','Chad','AF','N Djamena'),
(216,'Terras Austrais e Antárticas Francesas','French Southern Territories','AN','Port-aux-Francais'),
(217,'Togo','Togo','AF','Lome'),
(218,'Tailândia','Thailand','AS','Bangkok'),
(219,'Tadjiquistao','Tajikistan','AS','Dushanbe'),
(220,'Toquelau, Ilhas','Tokelau',' OC',''),
(221,'Timor Leste','East Timor','OC','Dili'),
(222,'Turcomenistão','Turkmenistan','AS','Ashgabat'),
(223,'Tunísia','Tunisia','AF','Tunis'),
(224,'Tonga','Tonga','OC','Nuku alofa'),
(225,'Turquia','Turkey','AS','Ankara'),
(226,'Trinidad e Tobago','Trinidad and Tobago','NA','Port of Spain'),
(227,'Tuvalu','Tuvalu','OC','Funafuti'),
(228,'Formosa (Taiwan)','Taiwan, Province of China','AS','Taipei'),
(229,'Republica Unida da Tanzânia','United Republic of Tanzania','AF','Dodoma'),
(230,'Ucrânia','Ukraine','EU','Kiev'),
(231,'Uganda','Uganda','AF','Kampala'),
(232,'Ilhas Menores Distantes dos Estados Unidos','United States Minor Outlying Islands',' OC',''),
(233,'Estados Unidos','United States','NA','Washington'),
(234,'Uruguai','Uruguay','SA','Montevideo'),
(235,'Uzbequistão','Uzbekistan','AS','Tashkent'),
(236,'Vaticano, Estado da Cidade do','Holy See (Vatican City State)','EU','Vatican City'),
(237,'São Vicente e Granadinas','Saint Vincent and the Grenadines','NA','Kingstown'),
(238,'Venezuela','Venezuela','SA','Caracas'),
(239,'Virgens, Ilhas (Britânicas)','Virgin Islands (British)','NA','Road Town'),
(240,'Virgens, Ilhas (E.U.A.)','Virgin Islands (U.S.)','NA','Charlotte Amalie'),
(241,'Vietnã','Viet Nam','AS','Hanoi'),
(242,'Vanuatu','Vanuatu','OC','Port Vila'),
(243,'Wallis e Futuna, Ilhas','Wallis and Futuna Islands','OC','Mata Utu'),
(244,'Samoa','Samoa','OC','Apia'),
(245,'Iémen','Yemen','AS','Sanaa'),
(246,'Mayotte (Ilhas Francesas)','Mayotte','AF','Mamoudzou'),
(247,'África do Sul','South Africa','AF','Pretoria'),
(248,'Zâmbia','Zambia','AF','Lusaka'),
(249,'Zimbabue','Zimbabwe','AF','Harare'),
(250,'Iugoslávia','Yugoslavia','EU','Belgrado'),
(251,'Ilhas Canarias','Canarias','AF','Las Palmas, Santa Cruz de Tenerife'),
(252,'Bonaire','Bonaire','SA','Kralendijk'),
(253,'Sérvia e Montenegro','Serbia and Montenegro','EU','Belgrade'),
(254,'Kosovo','Kosovo','EU','Pristina') ; 
